### ISSUE TITLE
La eraro ALREADY_LOGGED_IN povas okazi se la paĝo ne estas ĝisdata

### ISSUE THREAD

**Issue by RibeiroAna** [tejoesperanto/centra-reto#4]
Saluton,

Mi kreis mian profilon per telefono kaj mi volis plurigardi la reton per komputilo por vidi pli detale la funkciojn, sed kiam mi provis ensaluti per ĝi, mi ricevis la jenan mesaĝon:

```
{
  "success": false,
  "error": "ALREADY_LOGGED_IN",
  "url": "/api/user/login",
  "info": [],
  "frontend_location": "https://reto.tejo.org/ensaluti?//",
  "frontend_useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0",
  "frontend_time": "2019-01-09T12:21:05Z"
}
```
Laŭ la mesaĝo, mi kredas ke mi ne sukcesis ĉar mi jam estas ensalutita per mia poŝtelefono, kaj kroma problemo estis ke mi perdis mian sesion poŝtelefone (mi ensalutis per ena navegilo de Gmail ĉar mi klakis je ligilo tiel, kaj je neniu navegilo de poŝtelefono mi daŭre estas ensalutita) sed ne plu sukcesas ensaluti.

**Comment by miestasmia** [comment]
Saluton. Tute eblas ensaluti samtempe per pluraj iloj. La eraro `ALREADY_LOGGED_IN` signifas, ke ial estis sendita peto al `/api/user/login` de ilo kiu jam estis ensalutinta. Se vi povas transdoni al mi pli da informoj pri kion vi ekzakte faris, eblus eltrovi kial tio okazis, sed estas neniu kroma eraro.

La sesioj dependas je kuketoj, do se vi ensalutas per unu retumilo kaj poste ekuzas alian retumilon, la kuketo ne transiros. Tio estas tute laŭnorma implemento.

**Comment by miestasmia** [comment]
Unu eblo estus unue elsaluti se oni jam estas ensalutinta kiam oni provas ensaluti.

**Comment by RibeiroAna** [comment]
Tre strange... Kio okazis al mi estis ke unue aperis erarmesaĝo kiam mi provis ensaluti, mi decidis ignori ĝin (ne estis speciala mesaĝo, domaĝe mi ne kopiis) kaj provi denove, sed kiam mi provis denove kaj denove aperis tiu mesaĝo, do mi supozis ke temis pri tio ke mi estis ensalutita poŝtelefone. Mi purigis la kuketojn kaj reprovis kaj ĉio funkciis bone.

**Comment by miestasmia** [comment]
Solved in https://github.com/tejoesperanto/centra-reto/commit/8ff6e66779abe1e01db64dac103c291906455ef6
